[build-system]
requires = [
        "setuptools",
        "wheel",
        "cython",
        "numpy",
]

[flake8]
style = "numpy"
check-return-types = false
exclude = "docs"
extend-ignore = "E501,F401,E128,E231,E124,SIM114,DOC105,DOC106,DOC107,DOC301,DOC501,DOC503,DOC203,B006,SIM102,SIM113,DOC202,DOC403,DOC404"
per-file-ignores = ["ultranest/plot.py: B006", "ultranest/integrator.py: B006"]

[tool.pycodestyle]
count = false
ignore = "W191,W291,W293,E231,E225"
max-line-length = 160
statistics = false

[tool.pytest.ini_options]
collect_ignore = "['setup.py']"
addopts = "--junitxml=test-reports/junit.xml  --html=tests/reports/index.html"

[tool.pydocstyle]
add-ignore = "D107"

[project.urls]
Homepage = "https://github.com/JohannesBuchner/UltraNest"
Source = "https://github.com/JohannesBuchner/UltraNest"
Documentation = "https://johannesbuchner.github.io/UltraNest/"
